/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
--begin założenie bazy danych begin
CREATE DATABASE [PROJEKT70762]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROJEKT70762', FILENAME = N'V:\Microsoft SQL Server\MSSQL13.SQL2016D\MSSQL\DATA\PROJEKT70762.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PROJEKT70762_log', FILENAME = N'V:\Microsoft SQL Server\MSSQL13.SQL2016D\MSSQL\DATA\PROJEKT70762_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PROJEKT70762] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [PROJEKT70762] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PROJEKT70762] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PROJEKT70762] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PROJEKT70762] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PROJEKT70762] SET ARITHABORT OFF 
GO
ALTER DATABASE [PROJEKT70762] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PROJEKT70762] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PROJEKT70762] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PROJEKT70762] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PROJEKT70762] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PROJEKT70762] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PROJEKT70762] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PROJEKT70762] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PROJEKT70762] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PROJEKT70762] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PROJEKT70762] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PROJEKT70762] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PROJEKT70762] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PROJEKT70762] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PROJEKT70762] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PROJEKT70762] SET  READ_WRITE 
GO
ALTER DATABASE [PROJEKT70762] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PROJEKT70762] SET  MULTI_USER 
GO
ALTER DATABASE [PROJEKT70762] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PROJEKT70762] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PROJEKT70762] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PROJEKT70762]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PROJEKT70762]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PROJEKT70762] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
--end założenie bazy danych begin